### ISSUE TITLE
Routes/filter/template? for individual tickets

### ISSUE THREAD

**Issue by mpaddock** [UK-AS-HIVE/Triage#17]
Need either a filter string or a route to link to individual tickets.

**Comment by mpaddock** [comment]
I'm thinking a ?ticketId=123987139 or something to that effect would be fine, with the presence of a ticketId filter overriding other filters? A template probably isn't necessary.

**Comment by noahadler** [comment]
Now that we've settled on single queue/ticket, would it make sense to set up a route as a shortcut? like /ticket/1234 redirects to /queue/:queueOf1234/?ticketNo=1234

**Comment by mpaddock** [comment]
I'm going back and forth. That'd be fine as long as we auto-expand the ticket, and we could give the ticketNo as a clearable search-type field in the sidebar to let them go back to the full queue view. Alternately, maybe there should be a page that just shows the single ticket for linking to customers? I don't think that's necessary, but it might be nice so as not to confuse them with queue features if they don't need them.

**Comment by mpaddock** [comment]
Moving this into backlog until we decide on the design.
