### ISSUE TITLE
Only check security groups for queues when a user logs in?

### ISSUE THREAD

**Issue by noahadler** [UK-AS-HIVE/Triage#2]
Proposal: remove securityGroups from Queue collection.  Instead of checking against the Queue collection, check against the settings when a user logs in, and update their membership appropriately in the Queue.members field.

I think this would make things simpler, and keep the configuration a little more separate from core functionality.  Thoughts?

**Comment by mpaddock** [comment]
Agreed. I generally wasn't happy with the way queue membership was being handled, but hadn't thought of a different way. To be done via Deps.autorun on Meteor.userId?

**Comment by noahadler** [comment]
Looks like that should be a sensible way to do it, although I have a nagging feeling it didn't always work well on server.  According to the current docs, though, that looks like it should work just fine.  If we end up using mizzao:user-status (which is pretty nice imho) that has an event emitter we could use instead.

**Comment by mpaddock** [comment]
Okay - this is done on login now, but it's still checking against Queues.securityGroups for the moment. Have to run to class, but I'll update it to check against Meteor.settings this afternoon.

**Comment by mpaddock** [comment]
This is done but not committed as of yet - I've done this a couple of different ways and I don't love any of them. Mongo matches an array of regex's to an array of strings pretty easily, but I'm not sure if there's an efficient way to do that in JS, and all of my solutions have involved nested loops. We can talk about this in person tomorrow, but I'm tabling this for now - we've got 3 or 4 solutions and can decide on the best.
