### ISSUE TITLE
New Ticket dialog

### ISSUE THREAD

**Issue by noahadler** [UK-AS-HIVE/Triage#3]
- Queue should be a single required field, not checkboxes
- Would be nice if text box had full dialog width, maybe place label above instead of inline
- Tags?

**Comment by mpaddock** [comment]
- Disagree, and we've had discussions to this point (i.e. the first bullet point in the planning document). 
- Sounds fine.
- They're automatically picked up (both user and hash) and added to the ticket from the title/body, but there's no indicator that's that happening (and no display of tags within the ticket row as of yet). Any fields that would allow tagging need autocomplete support probably.

**Comment by mpaddock** [comment]
Modal is updated to full width, tags are again picking up correctly from body/title. Tags are displayed in ticket rows now although they don't do anything and they look dumb. Should we go ahead and look into adding mizzao:autocomplete to fields for tagging at this point?

**Comment by mpaddock** [comment]
Still need to update the queue checkboxes to something less ugly.

**Comment by mpaddock** [comment]
Changed this to a normal multiselect for now. Tried chosen.js (as this doesn't really need to be a reactive data source - queues can only be updated on server restart), but it won't even consistently give options in the dropdown.

**Comment by mpaddock** [comment]
Select2 works fine for the queue selection. 

Do we want there to be a separate field for tags? Or are we fine with just picking them up with # from the body/title as is going now?

**Comment by noahadler** [comment]
Based on how I've seen people using tags, I think a separate field would be
nice.  Our users don't seem to be hashtag aficionados.  Just my opinion.
Maybe we should first figure out how we want tags to work in the ticketRow,
and then come back to the new ticket dialog afterwards, and keep it
consistent?

**Comment by mpaddock** [comment]
Seems fair. Something similar to how it's working on Waggle right now would be fine, I think.

**Comment by mpaddock** [comment]
We still need to have a discussion about how to serve tags as a data source. (Maybe you know how to do this - ideally I'd like it to be a collection, either reactively generated from Tickets or maybe just updated on ticket insert).

**Comment by mpaddock** [comment]
Autocompleting usernames with the @ token in title/body fields now via mizzao:autocomplete. Tags are autocompleting for the standalone 'tag' field, but in a really janky way just for example - it won't scale and doesn't work as intended.

**Comment by noahadler** [comment]
Clear the form only when the 'x' or a 'Cancel' button is pushed, or the form is submitted.  In other words, don't clear the text just because the dialog gets dismissed.

**Comment by mpaddock** [comment]
Complete; the escape key check has to be a layout event and not in the template - it'll only detect the keypress in the template if a field is selected. I'm not sure where else we could put it unless we don't allow the ticket modal on every page.

**Comment by mpaddock** [comment]
Reopening - tags should pick up from the specific 'tags' input, default queue doesn't seem to be set anymore, autocomplete on tags needs to be working in the body.

**Comment by mpaddock** [comment]
Default queue is good. Tags pick up from the facet, which is possibly limited - look to expanding this.

**Comment by mpaddock** [comment]
Attempted to finish this on branch 'tags'. Added an observe to tickets to update a 'tags' collection on insert or update; also storing a 'last used' time for a tag and publishing the 100 most recently used tags so things don't get too out of hand. Autocompletes now complete from the tag collection appropriately.
