### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by mpaddock** [UK-AS-HIVE/Triage#30]

**Comment by mpaddock** [comment]
When do emails get sent?
- On ticket insert
- On ticket update for certain fields (status)
- On Changelog insert for type "note"

**Comment by noahadler** [comment]
Absolutely need some user preferences for this.  They are implemented in the old system, but don't save properly.  If we want to mirror those preferences, the following boolean options should be available:

IF I AM THE AUTHOR OF A STORY, EMAIL ME WHEN:
 I submit the story
 I leave a note on the story
 Someone else leaves a note on the story
 The status of the story changes

IF I AM ASSOCIATED WITH A STORY, EMAIL ME WHEN:
 I leave a note on the story
 Someone else leaves a note on the story
 The status of the story changes

**Comment by noahadler** [comment]
Attachments need special consideration as well.  For design, images will often be sent for approval, and email may be the most accessible way to communicate with clients.

**Comment by mpaddock** [comment]
The framework for sending this is in place although it needs some env variable/Meteor.settings considerations for deployment. Do we need more to the attachments (e.g. putting the actual attachments in the email), or is an email with a link to the ticket sufficient?

**Comment by noahadler** [comment]
I think it would be nice if we could include a medium-sized thumbnail for
attachments of pictures at least.  I don't think we need to send large
files.  I know this complicates things and doesn't fully answer the
question (sorry).
