### ISSUE TITLE
Modify waggle_webforms module to allow parallel Waggle/Triage ingestion

### ISSUE THREAD

**Issue by noahadler** [UK-AS-HIVE/Triage#33]
Can either clone it as another module and do a search/replace, or add an extra config option to the existing module to let it send to multiple locations.  We need this to begin the beta testing, so we can feed into both systems in case the new system breaks.

**Comment by noahadler** [comment]
Mostly implemented on triage branch of artsci_www.  Still need to split body fields into blackbox fields, and figure out how attachments should work without multipart submission.  Multipart submission seems out, since iron:router lacks good support for it.

**Comment by noahadler** [comment]
Still need to implement sending attachments to Triage.

**Comment by mpaddock** [comment]
Is this done? I was just testing github behavior

**Comment by noahadler** [comment]
Done enough.
