### ISSUE TITLE
Email ingestion

### ISSUE THREAD

**Issue by mpaddock** [UK-AS-HIVE/Triage#37]
Ingest responses to triagebot and add them as notes.

**Comment by noahadler** [comment]
Functionality should be a standalone script which accepts stdin from postfix containing the raw SMTP email, processes it, and makes an API call to Triage.

**Comment by noahadler** [comment]
Mostly implemented on the email branch

**Comment by noahadler** [comment]
Just waiting on postfix setup, implementation pretty much done.  Closing.
