### ISSUE TITLE
Ticket filtering and search

### ISSUE THREAD

**Issue by noahadler** [UK-AS-HIVE/Triage#4]
Use ?filter= in query string to define filters.  Any filters or facets in the right-hand sidebar (e.g., tags checkboxes) should update this filter string.

**Comment by noahadler** [comment]
We need something consistent that can be converted between the query string, mongo query objects, and serialized easily as DDP parameters for subscribing/method calls.  So something reactive that we can easily set from iron:router (parsing the query string), or update from any of the UI widgets, and make sure it all changes appropriately.

**Comment by noahadler** [comment]
Created a helper object Filter in lib/facets.coffee, that takes care of most of this.  I think we could still use some refinement.  Ideally, I'd like readable URLs, so maybe we want to strip out hashtags, commas, etc.  What about something like:

?search=search+phrase&search=a+second+phrase&tags=tagA+tagB&status=Open

**Comment by mpaddock** [comment]
Should we just strip the # out of the hashtags anyway? Waggle does this, and I'm not opposed to it.

**Comment by mpaddock** [comment]
The query string is encoded kind of weird...might have to look into forking iron-query if we want to actually use pluses. ._.

**Comment by noahadler** [comment]
Looks like it's fixed in the latest version of iron:url - https://github.com/iron-meteor/iron-url/commit/e373a06a7522881d8b8ee17a4879baffe9752418  I think if we wait, it will automatically start to use spaces when they publish a new version.

**Comment by mpaddock** [comment]
Parse for tags, statuses, users, etc.

**Comment by mpaddock** [comment]
Tag/status parsing working better. User parsing and search still todo.

**Comment by mpaddock** [comment]
User search done, although a little cleaning may be necessary. Need an easy way to clear the user search. Or a sidebar user box.

**Comment by mpaddock** [comment]
Closing this - the guts of it are done as far as I can tell, although it might need some UX consideration. Hopefully iron:url is updated soon as well.
