### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by noahadler** [UK-AS-HIVE/Triage#5]
Improve attachments functionality:
- Indicate attachments using paperclip icon
- Thumbnail preview when possible
- Larger preview inline with the notes/changelog (a la Asana)

**Comment by mpaddock** [comment]
- Make sure attachments are inserting into changelog

**Comment by mpaddock** [comment]
Uploading files seems to have broken/collapses rows on upload?

**Comment by noahadler** [comment]
Working decently, but still some bugs:
- Filename is needed to insert into changelog properly -- change Media.pickLocalFile API to add in callback parameter?
- Better serving of whole files, especially distinguishing based on MIME-type... figure out what server-side routes to set up for different use cases of serving files

**Comment by mpaddock** [comment]
How do we feel about this? Filename is inserting properly and downloading works fine (although probably not perfectly).  Should the rest of this be moved into a file-registry issue?

**Comment by noahadler** [comment]
I agree with that, and the MIME thing is done already.  Closing.
