### ISSUE TITLE
Limit/page data published to clients

### ISSUE THREAD

**Issue by noahadler** [UK-AS-HIVE/Triage#7]
Stress test: insert absurd amount (thousands?) of documents into all collections on server.  Make sure clients page the data as needed instead of trying to load it all and crashing.

**Comment by mpaddock** [comment]
Gave this a shot, although it needs some cleaning up. Clients page 30 tickets at a time now, and only tickets for the queue they're currently in. With over 5k documents on my dev machine, paging was very fast. One issue is the lack of a limit on paging - while I have it capped to 500 documents, clients can scroll down and load the whole 500 so quickly that it slows the browser some.

**Comment by mpaddock** [comment]
Yeah, very rough browser performance while data is loading. Need to cap it or make sure it's loading on demand.
